spring:
  application:
    name: oauth2-resource
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:58084/oauth2-server/oauth/token
      user-authorization-uri: http://localhost:58084/oauth2-server/oauth/authorize
    resource:
      token-info-uri: http://localhost:58084/oauth2-server/oauth/check_token
    
server:
  port: 58092
  servlet:
    context-path: /oauth2-resource
    session:
      cookie:
        name: OAUTH2SESSION