server:
   port: 8555
spring:
    application:
        name: api-gateway # 项目名称尽量用小写 
eureka:
  # 配置开启健康检查
   client:
      healthcheck:
         enabled: true
      serviceUrl:
         defaultZone: http://localhost:9000/eureka/ # 指定注册中心的地址
