spring:
  application:
    name: oauth2-resource
    
oauth2-server-url: http://localhost:58084/oauth2-server
security:
  oauth2: #与oauth2-server对应的配置
    client:
      client-id: sheep1
      client-secret: 123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
#security:
#  oauth2:
#    client:
#      client-id: sheep1
#      client-secret: 123456
#      access-token-uri: ${oauth2-server-url}/oauth/token
#      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
#      client-authentication-scheme: form
#    resource:
#      #token-info-uri: ${oauth2-server-url}/oauth/check_token
#      jwt:
#        key-uri: ${oauth2-server-url}/oauth/token_key
#  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
#  sessions: ALWAYS
      
server:
  port: 58093
  servlet:
    context-path: /oauth2-resource
    session:
      cookie:
        name: OAUTH2-CLINT-SESSION